# Generated by Django 3.1.2 on 2021-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(max_length=255, verbose_name='Зміст'),
        ),
    ]
