# Generated by Django 3.1.2 on 2021-09-09 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('employee_lastname', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('employee_position', models.CharField(blank=True, max_length=150, verbose_name='посада')),
                ('employee_address', models.CharField(blank=True, max_length=255, verbose_name='адреса')),
                ('employee_phone', models.CharField(blank=True, max_length=255, verbose_name='телефон')),
                ('employee_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('employee_birthday', models.DateField(blank=True, null=True, verbose_name='дата народження')),
                ('employee_status', models.CharField(blank=True, max_length=255, verbose_name='сімейний стан')),
                ('employee_education', models.TextField(blank=True, verbose_name='освіта')),
                ('employee_profile', models.TextField(blank=True, verbose_name='профіль')),
                ('employee_skills', models.CharField(blank=True, help_text='Ведіть Ваш досвід роботи коротко, через кому та без пробілу', max_length=255, verbose_name='досвід')),
                ('employee_notes', models.TextField(blank=True, verbose_name='примітки')),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='зображення')),
            ],
            options={
                'verbose_name': 'співробітник',
                'verbose_name_plural': 'співробітники',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('contact_subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('contact_message', models.TextField(blank=True, max_length=150, verbose_name='message')),
                ('contact_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакти',
            },
        ),
    ]
