# Generated by Django 3.1.2 on 2021-03-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('contact_subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('contact_message', models.TextField(blank=True, max_length=150, verbose_name='message')),
                ('contact_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакти',
            },
        ),
    ]
