# Generated by Django 3.1.2 on 2021-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('employee_lastname', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('employee_position', models.CharField(blank=True, max_length=150, verbose_name='посада')),
                ('employee_address', models.CharField(blank=True, max_length=255, verbose_name='адреса')),
                ('employee_phone', models.CharField(blank=True, max_length=255, verbose_name='телефон')),
                ('employee_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('employee_profile', models.TextField(blank=True, verbose_name='профіль')),
            ],
            options={
                'verbose_name': 'співробітник',
                'verbose_name_plural': 'співробітники',
            },
        ),
    ]
