# Generated by Django 3.1.2 on 2021-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='зображення'),
        ),
    ]
