# Generated by Django 3.1.2 on 2021-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_employee_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата народження'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='сімейний стан'),
        ),
    ]
