# Generated by Django 3.1.2 on 2021-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210417_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата народження'),
        ),
    ]
