# Generated by Django 3.1.2 on 2021-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210417_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_education',
            field=models.TextField(blank=True, verbose_name='освіта'),
        ),
    ]
