# Generated by Django 3.1.2 on 2021-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_employee_employee_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_skills',
            field=models.CharField(blank=True, help_text='Ведіть Ваш досвід роботи коротко, через кому та без пробілу', max_length=255, verbose_name='досвід'),
        ),
    ]
