# Generated by Django 3.1.2 on 2021-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rss_url', models.URLField()),
                ('date_format', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Enter tags for search using whitespaces between', max_length=255)),
            ],
            options={
                'verbose_name': 'Джерело законодавства',
                'verbose_name_plural': 'Джерела законодавства',
                'ordering': ('publisher',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rss_url', models.URLField()),
                ('date_format', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Enter tags for search using whitespaces between', max_length=255)),
            ],
            options={
                'verbose_name': 'Джерело новин',
                'verbose_name_plural': 'Джерела новин',
                'ordering': ('publisher',),
            },
        ),
    ]
