# Generated by Django 3.1.2 on 2020-10-25 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер заявки')),
                ('order_created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('order_updated', models.DateTimeField(auto_now=True, verbose_name='дата створення')),
                ('order_regime', models.CharField(blank=True, max_length=255, null=True, verbose_name='митний режим')),
                ('order_vehicle', models.CharField(blank=True, max_length=8, null=True, verbose_name='вид транспорту')),
                ('exporter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='найменування юридичної особи/фізичної особи-підприємця')),
                ('exporter_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='юридична адреса')),
                ('exporter_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ')),
                ('cargo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='найменування вантажу')),
                ('cargo_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='код УКТЗЕД')),
                ('cargo_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='кількість вантажу, кг.')),
                ('cargo_addnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='кількість вантажу, додаткові одиниці виміру')),
                ('cargo_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='фактурна вартість товару з урахуванням транспортних видатків')),
                ('cargo_currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='валюта')),
                ('cargo_duties', models.CharField(blank=True, max_length=255, null=True, verbose_name='сума митних платежів, на які надається фінансова гарантія, грн.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
