# Generated by Django 3.1.2 on 2021-09-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='№')),
                ('order_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата створення')),
                ('order_updated', models.DateField(auto_now_add=True, verbose_name='дата редагування')),
                ('expired_date', models.DateField(default=django.utils.timezone.now, verbose_name='строк дії гарантії')),
                ('customs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customs', to='references.customsoffice', verbose_name='бенефіціар')),
                ('customs_departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customs_departure', to='references.customsoffice', verbose_name='митниця відправлення')),
                ('customs_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customs_destination', to='references.customsoffice', verbose_name='митниця призначення')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_principal', to='references.company', verbose_name='принципал')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure', to='references.warrantyprocedure', verbose_name='процедура')),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='regime', to='references.customsregime', verbose_name='митний режим')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle', to='references.vehicletype', verbose_name='транспорт')),
                ('warranty_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warranty_type', to='references.warrantytype', verbose_name='послуга')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='UploadDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='uploads/documents/%Y/%m/%d/', verbose_name='завантажити файл')),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва документа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaddocs', to='orders.order')),
            ],
            options={
                'verbose_name': 'товаросупровідний документ',
                'verbose_name_plural': 'товаросупровідні документи',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='код УКТЗЕД')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='вага, кг.')),
                ('addnumber', models.PositiveIntegerField(blank=True, null=True, verbose_name='кількість')),
                ('duties', models.PositiveIntegerField(blank=True, null=True, verbose_name='платежі, грн.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='orders.order')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
            },
        ),
    ]
