# Generated by Django 3.1.2 on 2021-06-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20210621_1845'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exporter_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exporter_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exporter_name',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_carrier', to='references.company', verbose_name='перевізник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='exporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_exporter', to='references.company', verbose_name='експортер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='forwarder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_forwarder', to='references.company', verbose_name='експедитор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='importer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_importer', to='references.company', verbose_name='імпортер'),
            preserve_default=False,
        ),
    ]
