# Generated by Django 3.1.2 on 2021-06-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20210621_1919'),
        ('orders', '0003_auto_20210621_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_carrier', to='references.company', verbose_name='перевізник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_forwarder', to='references.company', verbose_name='експедитор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_importer', to='references.company', verbose_name='імпортер'),
        ),
    ]
