# Generated by Django 3.1.2 on 2021-06-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_customsregime_short_name'),
        ('orders', '0004_auto_20210621_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_customer', to='references.company', verbose_name='клієнт'),
        ),
    ]
