# Generated by Django 3.1.2 on 2021-08-20 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_auto_20210820_1928'),
        ('orders', '0005_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '4'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_carrier', to='references.company', verbose_name='перевізник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '1'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_customer', to='references.company', verbose_name='клієнт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '2'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_exporter', to='references.company', verbose_name='експортер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='forwarder',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '5'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_forwarder', to='references.company', verbose_name='експедитор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='importer',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '3'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_importer', to='references.company', verbose_name='імпортер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_updated',
            field=models.DateField(auto_now_add=True, verbose_name='дата редагування'),
        ),
    ]
