# Generated by Django 3.1.2 on 2021-08-20 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20210820_2017'),
        ('orders', '0006_auto_20210820_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cargo_duties',
            new_name='warranty_sum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_addnumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='forwarder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='importer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='regime',
        ),
        migrations.AddField(
            model_name='order',
            name='expired_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='строк дії гарантії'),
        ),
        migrations.AddField(
            model_name='order',
            name='principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': '6'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_principal', to='references.company', verbose_name='принципал'),
        ),
    ]
