# Generated by Django 3.1.2 on 2021-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210820_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='docs_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warranty_sum',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True, verbose_name='сума митних платежів, грн.'),
        ),
    ]
