# Generated by Django 3.1.2 on 2021-08-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20210820_2017'),
        ('orders', '0010_auto_20210820_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='docs_upload',
        ),
        migrations.AddField(
            model_name='order',
            name='customs_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customs_departure', to='references.customsoffice', verbose_name='митниця відправлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='customs_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customs_destination', to='references.customsoffice', verbose_name='митниця призначення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='номер заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warranty_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сума митних платежів, грн.'),
        ),
        migrations.CreateModel(
            name='UploadDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='uploads/documents/%Y/%m/%d/', verbose_name='завантажити файл')),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва документа')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaddocs', to='orders.order')),
            ],
            options={
                'verbose_name': 'товаросупровідний документ',
                'verbose_name_plural': 'товаросупровідні документи',
            },
        ),
    ]
