# Generated by Django 3.1.2 on 2021-08-22 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_warrantytype'),
        ('orders', '0012_auto_20210821_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expired_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='строк дії гарантії'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='order',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure', to='references.warrantyprocedure', verbose_name='процедура'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle', to='references.vehicletype', verbose_name='транспорт'),
        ),
    ]
