# Generated by Django 3.1.2 on 2021-08-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_auto_20210827_0029'),
        ('orders', '0015_auto_20210822_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_principal', to='references.company', verbose_name='принципал'),
        ),
    ]
