# Generated by Django 3.1.2 on 2021-08-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_auto_20210827_1415'),
        ('orders', '0016_auto_20210827_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='regime', to='references.customsregime', verbose_name='митний режим'),
        ),
    ]
