# Generated by Django 3.1.2 on 2021-08-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_auto_20210827_1415'),
        ('orders', '0017_order_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_carrier', to='references.company', verbose_name='перевізник'),
        ),
        migrations.AddField(
            model_name='order',
            name='exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_exporter', to='references.company', verbose_name='експортер'),
        ),
        migrations.AddField(
            model_name='order',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_forwarder', to='references.company', verbose_name='експедитор'),
        ),
        migrations.AddField(
            model_name='order',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_importer', to='references.company', verbose_name='імпортер'),
        ),
    ]
