# Generated by Django 3.1.2 on 2021-08-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210827_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='forwarder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='importer',
        ),
        migrations.AlterField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='orders.order'),
            preserve_default=False,
        ),
    ]
