# Generated by Django 3.1.2 on 2021-09-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='код')),
                ('currency_letter', models.CharField(blank=True, max_length=3, null=True, verbose_name='літерний код')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюти',
            },
        ),
        migrations.CreateModel(
            name='CustomsEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='напрямок переміщення')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код напрямку')),
                ('feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='особливості декларування')),
                ('type_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код типу')),
            ],
            options={
                'verbose_name': 'тип декларації',
                'verbose_name_plural': 'типи декларацій',
            },
        ),
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='код')),
                ('office_attr', models.CharField(blank=True, max_length=3, null=True, verbose_name='ознака')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('office_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='область')),
                ('office_locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='пункт')),
                ('office_zip', models.CharField(blank=True, max_length=5, null=True, verbose_name='індекс')),
                ('office_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва вулиці')),
            ],
            options={
                'verbose_name': 'митний підрозділ',
                'verbose_name_plural': 'митні підрозділи',
            },
        ),
        migrations.CreateModel(
            name='CustomsRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='скорочена назва')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='гарантування')),
            ],
            options={
                'verbose_name': 'митний режим',
                'verbose_name_plural': 'митні режими',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='код')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='найменування')),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документи',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип транспорту')),
                ('vehicle_type_code', models.CharField(blank=True, max_length=1, null=True, verbose_name='код типу')),
                ('vehicle_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код транспорту')),
                ('vehicle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'вид транспорту',
                'verbose_name_plural': 'види транспорту',
            },
        ),
        migrations.CreateModel(
            name='WarrantyProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='код')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'процедура гарантування',
                'verbose_name_plural': 'процедури гарантування',
            },
        ),
        migrations.CreateModel(
            name='WarrantyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='вид послуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='опис послуги')),
            ],
            options={
                'verbose_name': 'вид послуги',
                'verbose_name_plural': 'види послуг',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ')),
                ('tax', models.CharField(blank=True, max_length=10, null=True, verbose_name='ІПН')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='керівник')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='телефон')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='активна')),
                ('blacklist', models.BooleanField(blank=True, null=True, verbose_name='чорний список')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'компанія',
                'verbose_name_plural': 'компанії',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='суміжна країна')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='довгота')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='примітки')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='references.vehicletype', verbose_name='транспорт')),
            ],
            options={
                'verbose_name': 'представник',
                'verbose_name_plural': 'представники',
            },
        ),
    ]
