# Generated by Django 3.1.2 on 2021-04-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='код')),
                ('currency_letter', models.CharField(blank=True, max_length=3, null=True, verbose_name='літерний код')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюти',
            },
        ),
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='код підрозділу')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'митний підрозділ',
                'verbose_name_plural': 'митні підрозділи',
            },
        ),
        migrations.CreateModel(
            name='CustomsRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='напрямок переміщення')),
                ('regime_type_code', models.CharField(blank=True, max_length=1, null=True, verbose_name='код напрямку')),
                ('regime_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код режиму')),
                ('regime_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'митний режим',
                'verbose_name_plural': 'митні режими',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип')),
                ('document_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='код')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='найменування')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документи',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип транспорту')),
                ('vehicle_type_code', models.CharField(blank=True, max_length=1, null=True, verbose_name='код типу')),
                ('vehicle_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код транспорту')),
                ('vehicle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'вид транспорту',
                'verbose_name_plural': 'види транспорту',
            },
        ),
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarder_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна реєстрації')),
                ('forwarder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('forwarder_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('forwarder_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('forwarder_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forwarder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'експедитор',
                'verbose_name_plural': 'експедитори',
            },
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignor_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна реєстрації')),
                ('consignor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('consignor_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('consignor_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('consignor_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consignor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'відправник',
                'verbose_name_plural': 'відправники',
            },
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна реєстрації')),
                ('consignee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('consignee_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('consignee_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('consignee_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'одержувач',
                'verbose_name_plural': 'одержувачі',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна реєстрації')),
                ('carrier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('carrier_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('carrier_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('carrier_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carrier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'перевізник',
                'verbose_name_plural': 'перевізники',
            },
        ),
    ]
