# Generated by Django 3.1.2 on 2021-10-26 17:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='примітки'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='references.vehicletype', verbose_name='транспорт'),
        ),
    ]
