# Generated by Django 3.1.2 on 2021-04-21 15:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='суміжна країна')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='довгота')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='примітки')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='references.vehicletype')),
            ],
            options={
                'verbose_name': 'представник',
                'verbose_name_plural': 'представники',
            },
        ),
    ]
