# Generated by Django 3.1.2 on 2021-05-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsoffice',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='назва вулиці'),
        ),
        migrations.AddField(
            model_name='customsoffice',
            name='office_attr',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ознака'),
        ),
        migrations.AddField(
            model_name='customsoffice',
            name='office_locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='населений пункт'),
        ),
        migrations.AddField(
            model_name='customsoffice',
            name='office_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='область'),
        ),
        migrations.AddField(
            model_name='customsoffice',
            name='office_zip',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='індекс'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='references.vehicletype', verbose_name='транспорт'),
        ),
        migrations.AlterField(
            model_name='customsoffice',
            name='office_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='код'),
        ),
    ]
