# Generated by Django 3.1.2 on 2021-05-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20210502_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsoffice',
            name='office_locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='пункт'),
        ),
    ]
