# Generated by Django 3.1.2 on 2021-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20210502_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='напрямок переміщення')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код напрямку')),
                ('feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='особливості декларування')),
                ('type_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='код типу')),
            ],
            options={
                'verbose_name': 'тип декларації',
                'verbose_name_plural': 'типи декларацій',
            },
        ),
        migrations.RenameField(
            model_name='customsregime',
            old_name='regime_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customsregime',
            name='regime_code',
        ),
        migrations.RemoveField(
            model_name='customsregime',
            name='regime_type',
        ),
        migrations.RemoveField(
            model_name='customsregime',
            name='regime_type_code',
        ),
        migrations.AddField(
            model_name='customsregime',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='код'),
        ),
    ]
