# Generated by Django 3.1.2 on 2021-05-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20210504_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='doc_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_name',
            new_name='name',
        ),
    ]
