# Generated by Django 3.1.2 on 2021-06-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0006_auto_20210504_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ')),
                ('tax', models.CharField(blank=True, max_length=10, null=True, verbose_name='ІПН')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='контактний телефон')),
                ('blacklist', models.BooleanField(blank=True, null=True, verbose_name='адреса')),
            ],
            options={
                'verbose_name': 'компанія',
                'verbose_name_plural': 'компанії',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='статус')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.RemoveField(
            model_name='consignee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forwarder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.DeleteModel(
            name='Consignee',
        ),
        migrations.DeleteModel(
            name='Consignor',
        ),
        migrations.DeleteModel(
            name='Forwarder',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ManyToManyField(to='references.CompanyStatus'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
