# Generated by Django 3.1.2 on 2021-06-21 15:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20210621_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystatus',
            options={'ordering': ['status'], 'verbose_name': 'статус компанії', 'verbose_name_plural': 'статуси компаній'},
        ),
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='керівник'),
        ),
        migrations.AlterField(
            model_name='company',
            name='blacklist',
            field=models.BooleanField(blank=True, default=1, verbose_name='чорний список'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='поштова скринька'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='контактний телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ManyToManyField(to='references.CompanyStatus', verbose_name='статус'),
        ),
    ]
