# Generated by Django 3.1.2 on 2021-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20210621_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, to='references.CompanyStatus', verbose_name='статус'),
        ),
    ]
