# Generated by Django 3.1.2 on 2021-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20210621_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsregime',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='скорочена назва'),
        ),
    ]
