# Generated by Django 3.1.2 on 2021-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_auto_20210820_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyprocedure',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='код'),
        ),
    ]
