# Generated by Django 3.1.2 on 2021-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20210820_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='вид послуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='опис послуги')),
            ],
        ),
    ]
