# Generated by Django 3.1.2 on 2021-08-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_warrantytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrantytype',
            options={'verbose_name': 'вид послуги', 'verbose_name_plural': 'види послуг'},
        ),
    ]
