# Generated by Django 3.1.2 on 2021-08-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_auto_20210827_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='blacklist',
            field=models.BooleanField(blank=True, null=True, verbose_name='чорний список'),
        ),
    ]
