# Generated by Django 3.1.2 on 2021-08-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_auto_20210827_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='статус'),
        ),
    ]
