# Generated by Django 3.1.2 on 2021-08-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0017_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='статус'),
        ),
    ]
