# Generated by Django 3.1.2 on 2021-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_customsregime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsregime',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='гарантування'),
        ),
    ]
