# Generated by Django 3.1.2 on 2021-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_auto_20210827_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='активна'),
        ),
    ]
