# Generated by Django 3.1.2 on 2021-10-26 16:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_auto_20211026_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='примітки'),
        ),
    ]
